# Generated by Django 5.1.3 on 2024-12-03 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False, help_text="상단 고정 여부")),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "start_date",
                    models.DateTimeField(blank=True, help_text="공지 시작일시", null=True),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, help_text="공지 종료일시", null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항",
                "verbose_name_plural": "공지사항 목록",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoticeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="첨부파일 (최대 10MB)", upload_to="notices/files/%Y/%m/%d/"
                    ),
                ),
                ("filename", models.CharField(help_text="원본 파일명", max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="파일 크기 (bytes)")),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="notices.notice",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항 첨부파일",
                "verbose_name_plural": "공지사항 첨부파일 목록",
                "ordering": ["notice", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="NoticeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="notices/%Y/%m/%d/")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, help_text="이미지 순서"),
                ),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="notices.notice",
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항 이미지",
                "verbose_name_plural": "공지사항 이미지 목록",
                "ordering": ["notice", "order"],
            },
        ),
        migrations.CreateModel(
            name="NoticeRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="notices.notice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notice_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "공지사항 읽음",
                "verbose_name_plural": "공지사항 읽음 목록",
            },
        ),
        migrations.AddIndex(
            model_name="notice",
            index=models.Index(
                fields=["is_pinned", "-created_at"],
                name="notices_not_is_pinn_e263db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noticeread",
            index=models.Index(
                fields=["user", "notice"], name="notices_not_user_id_74fee3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noticeread",
            unique_together={("notice", "user")},
        ),
    ]
