# Generated by Django 5.1.3 on 2024-12-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "수컷"), ("F", "암컷")], max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pet",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="pets/"),
        ),
        migrations.AlterField(
            model_name="pet",
            name="size",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="pet",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
