# Generated by Django 5.1.3 on 2024-12-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_alter_pet_options_pet_gender_alter_pet_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="additional_image",
            field=models.ImageField(blank=True, null=True, upload_to="pets/"),
        ),
    ]
