# Generated by Django 5.1.3 on 2024-12-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_likes_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "게시글",
                "verbose_name_plural": "게시글 목록",
            },
        ),
        migrations.AddField(
            model_name="comment",
            name="level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
