# Generated by Django 5.1.3 on 2024-12-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_options_comment_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("notice", "공지사항"),
                    ("dog", "강아지 커뮤니티"),
                    ("mate", "산책메이트 커뮤니티"),
                ],
                max_length=20,
            ),
        ),
    ]
