# Generated by Django 5.1.3 on 2024-12-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("district", models.CharField(max_length=50)),
                ("neighborhood", models.CharField(max_length=50)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                (
                    "precipitation",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "precipitation_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("walking_score", models.IntegerField(default=0)),
                ("forecast_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "weather_data",
                "indexes": [
                    models.Index(
                        fields=["district", "neighborhood"],
                        name="weather_dat_distric_921729_idx",
                    ),
                    models.Index(
                        fields=["forecast_time"], name="weather_dat_forecas_5bc979_idx"
                    ),
                ],
                "unique_together": {("district", "neighborhood", "forecast_time")},
            },
        ),
        migrations.CreateModel(
            name="WalkingCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommendation", models.CharField(max_length=200)),
                ("warning", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "weather_data",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="walking_condition",
                        to="weathers.weatherdata",
                    ),
                ),
            ],
            options={
                "db_table": "walking_conditions",
            },
        ),
    ]
