# Generated by Django 5.1.3 on 2024-12-10 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weathers", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="WalkingCondition",
        ),
        migrations.DeleteModel(
            name="WeatherData",
        ),
    ]
