# Generated by Django 5.1.3 on 2024-12-04 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="자기소개를 500자 이내로 작성하세요.",
                max_length=500,
                validators=[django.core.validators.MaxLengthValidator(500)],
            ),
        ),
    ]
